Salsify/RailsApplicationSerializer:
  Description: 'Serializers must subclass ApplicationSerializer.'
  Enabled: false

Salsify/RailsApplicationRecord:
  Description: 'Models must subclass ApplicationRecord.'
  Enabled: false

Salsify/RspecDocString:
  Description: 'Check that RSpec doc strings use the correct quoting.'
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  Include:
    - 'spec/**/*'

Salsify/RspecDotNotSelfDot:
  Description: 'Enforce ".<class method>" instead of "self.<class method>" for example group description.'
  Enabled: true
  Include:
    - 'spec/**/*'

Salsify/RspecStringLiterals:
  Description: 'Enforce consistent quote style for non-doc strings in RSpec tests.'
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  Include:
    - 'spec/**/*'

Salsify/StyleDig:
  Description: 'Recommend `dig` for deeply nested access.'
  Enabled: true
  AutoCorrect: false

